### ISSUE TITLE
fail build

### ISSUE THREAD

**Issue by sl1pkn07** [vkmark/vkmark#22]
~~~
[9/67] Compiling C++ object 'src/25a6634@@vkmark@exe/vkutil_pipeline_builder.cpp.o'.
FAILED: src/25a6634@@vkmark@exe/vkutil_pipeline_builder.cpp.o 
c++ -Isrc/25a6634@@vkmark@exe -Isrc -I../src -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -g '-DVKMARK_WINDOW_SYSTEM_DIR="/usr/lib/vkmark"' '-DVKMARK_DATA_DIR="/usr/share/vkmark"' '-DVKMARK_VERSION_STR="2017.08"' -march=native -O2 -fno-plt -D_FORTIFY_SOURCE=2 -MD -MQ 'src/25a6634@@vkmark@exe/vkutil_pipeline_builder.cpp.o' -MF 'src/25a6634@@vkmark@exe/vkutil_pipeline_builder.cpp.o.d' -o 'src/25a6634@@vkmark@exe/vkutil_pipeline_builder.cpp.o' -c ../src/vkutil/pipeline_builder.cpp
../src/vkutil/pipeline_builder.cpp: En la función miembro ‘ManagedResource<vk::Pipeline> vkutil::PipelineBuilder::build()’:
../src/vkutil/pipeline_builder.cpp:206:78: error: no matching function for call to ‘ManagedResource<vk::Pipeline>::ManagedResource(<brace-enclosed initializer list>)’
  206 |         [vptr=&vulkan] (auto const& p) { vptr->device().destroyPipeline(p); }};
~~~

vulkan 1.1.136

**Comment by afrantzis** [comment]
Hi! Which compiler and version are you using?

**Comment by sl1pkn07** [comment]
gcc 9.3.0

**Comment by Korvox** [comment]
Diagnostics saying its a binding issue.
```
FAILED: src/25a6634@@vkmark@exe/vkutil_pipeline_builder.cpp.o 
c++ -Isrc/25a6634@@vkmark@exe -Isrc -I../src -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -g '-DVKMARK_WINDOW_SYSTEM_DIR="/usr/lib/vkmark"' '-DVKMARK_DATA_DIR="/usr/share/vkmark"' '-DVKMARK_VERSION_STR="2017.08"' -march=x86-64 -mtune=generic -O2 -fno-plt -D_FORTIFY_SOURCE=2 -MD -MQ 'src/25a6634@@vkmark@exe/vkutil_pipeline_builder.cpp.o' -MF 'src/25a6634@@vkmark@exe/vkutil_pipeline_builder.cpp.o.d' -o 'src/25a6634@@vkmark@exe/vkutil_pipeline_builder.cpp.o' -c ../src/vkutil/pipeline_builder.cpp
../src/vkutil/pipeline_builder.cpp: In member function ‘ManagedResource<vk::Pipeline> vkutil::PipelineBuilder::build()’:
../src/vkutil/pipeline_builder.cpp:205:47: error: cannot bind rvalue reference of type ‘vk::Pipeline&&’ to lvalue of type ‘vk::Pipeline’
  205 |         vulkan.device().createGraphicsPipeline({}, pipeline_create_info),
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/vkutil/pipeline_builder.h:25,
                 from ../src/vkutil/pipeline_builder.cpp:23:
```

**Comment by Korvox** [comment]
Looks like the signature of createGraphicsPipeline changed in vulkan-headers commit [7264358](https://github.com/KhronosGroup/Vulkan-Headers/commit/7264358702061d3ed819d62d3d6fd66ab1da33c3).
I checked and Arch (what I'm on) hasn't changed its build script for vulkan-headers this year.

[Heres the simplest fix I could come up with that gets it to compile.](https://github.com/vkmark/vkmark/files/4562549/0001-Fix-compliation-error-on-createGraphicsPipeline.patch.txt)

As an aside when compiling I ran into a runtime segfault when printing the device name at startup. Seems something doesn't like a char[255] but didn't mind it being casted to a char* because the benchmark ran fine like this. [Heres what both fixes looked like to get vkmark working again.](https://github.com/vkmark/vkmark/files/4562570/0001-Fix-compliation-error-on-createGraphicsPipeline.patch.txt)

**Comment by afrantzis** [comment]
@Korvox Thanks for the investigation!

After looking a bit more myself, I am inclined to think that this is something that should be fixed in the vulkan headers. I have filed a bug (and possible fix) for the vulkan headers here: https://github.com/KhronosGroup/Vulkan-Hpp/issues/589. Let's see what upstream says.

**Comment by afrantzis** [comment]
@Korvox Commit fb591d07 should take care of the second issue you mention (segfault while printing device name). Thanks!

**Comment by afrantzis** [comment]
A fix for this build failure was merged at https://github.com/KhronosGroup/Vulkan-Hpp/commit/18da9fdcfd2374c742c5a20d00239c62527aa599 and released in  https://github.com/KhronosGroup/Vulkan-Headers/releases/tag/v1.2.141.
