### ISSUE TITLE
vulkan/vulkan_intel.h: No such file or directory

### ISSUE THREAD

**Issue by Lucretia** [vkmark/vkmark#6]
I don't have that file on my system, I'm on Gentoo.

ninja: Entering directory `build'
[25/55] Compiling Cpp object 'src/kms@sha/ws_kms_window_system.cpp.o'.
FAILED: src/kms@sha/ws_kms_window_system.cpp.o 
c++  -Isrc/kms@sha -Isrc -I../src -I/usr/include/libdrm -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -O0 -g '-DVKMARK_WINDOW_SYSTEM_DIR="/usr/local/lib64/vkmark"' '-DVKMARK_DATA_DIR="/usr/local/share/vkmark"' '-DVKMARK_VERSION_STR="2017.07"' -fPIC -MMD -MQ 'src/kms@sha/ws_kms_window_system.cpp.o' -MF 'src/kms@sha/ws_kms_window_system.cpp.o.d' -o 'src/kms@sha/ws_kms_window_system.cpp.o' -c ../src/ws/kms_window_system.cpp
../src/ws/kms_window_system.cpp:32:33: fatal error: vulkan/vulkan_intel.h: No such file or directory
compilation terminated.
[34/55] Compiling Cpp object 'src/vkmark@exe/scenes_vertex_scene.cpp.o'.
ninja: build stopped: subcommand failed.

**Comment by Lucretia** [comment]
This should not rely on that header, it should be conditional.

**Comment by afrantzis** [comment]
Hmm, it seems that Debian and derivatives ship that header by default, but not other distros. Unfortunately the header is required for the KMS plugin to work, since there still isn't a vendor neutral vulkan extension to use dmabuf buffers. 

I will change the build logic to not build the KMS plugin automatically if the header is missing. In the meantime, as a quick workaround, use "meson -Dkms=false build" to build without kms.
